### ISSUE TITLE
make fails (macOS/clang)

### ISSUE THREAD

**Issue by mnemnion** [basic-gongfu/cixl#2]
Hi! 

I really like where you're going with cixl! I'm having trouble building it:

```
/Users/atman/Dropbox/Projects/code/opp/cixl/src/cixl/buf.c:9:18: error: implicit declaration of function 'open_memstream' is
      invalid in C99 [-Werror,-Wimplicit-function-declaration]
  buf->stream  = open_memstream (&buf->data, &buf->size);
                 ^
/Users/atman/Dropbox/Projects/code/opp/cixl/src/cixl/buf.c:9:16: error: incompatible integer to pointer conversion assigning to
      'FILE *' (aka 'struct __sFILE *') from 'int' [-Werror,-Wint-conversion]
  buf->stream  = open_memstream (&buf->data, &buf->size);
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/cixl.dir/src/cixl/buf.c.o] Error 1
make[1]: *** [CMakeFiles/cixl.dir/all] Error 2
make: *** [all] Error 2
```

I suspect these are clang/gcc differences rather than being Mac specific.

**Comment by ephetic** [comment]
This is the problem I'm having too. Apparently memstream doesn't exist on
Mac. There's a third party version you can build, but my C-fu has been too
weak to figured out how to link to it.

**Comment by ephetic** [comment]
http://piumarta.com/software/memstream/

**Comment by ephetic** [comment]
This is the problem I'm having too. Apparently, memstream doesn't exist on
Mac. There's a[ third party version](http://piumarta.com/software/memstream/) you can build, but my C-fu has been too
weak to figure out how to link to it.

**Comment by basic-gongfu** [comment]
Dang; my mac awareness isn't that great these days, been out of the loop for a long time. It's a POSIX extension, and it's unfortunately used extensively by cixl. 

Found this, which says macos 10.5 doesn't have it (and to me kind of implies later versions do):
https://www.gnu.org/software/gnulib/manual/html_node/open_005fmemstream.html

**Comment by ephetic** [comment]
10.11.6 seems not to.

**Comment by mnemnion** [comment]
It seems there is a BSD implementation: 

[http://piumarta.com/software/memstream/](http://piumarta.com/software/memstream/)

**Comment by mnemnion** [comment]
Ah I see that's been linked already!

**Comment by ephetic** [comment]
@mnemnion That's what I found to.  Lemme know if you figure out the right way to build/link to it.

**Comment by basic-gongfu** [comment]
I don't have a BSD available, and it unfortunately claims to not build on other platforms. But the first thing I would try is putting memstream.h/c into src/cixl, and include "cixl/memstream.h" from buf.c in the same dir.

**Comment by mnemnion** [comment]
That gets me this far:

```
Scanning dependencies of target cixl
[  2%] Building C object CMakeFiles/cixl.dir/src/cixl/buf.c.o
[  4%] Building C object CMakeFiles/cixl.dir/src/cixl/cmp.c.o
[  7%] Building C object CMakeFiles/cixl.dir/src/cixl/cx.c.o
/Users/atman/Dropbox/Projects/code/opp/cixl/src/cixl/cx.c:123:50: error: function definition is not allowed here
  void set(const char *id, struct cx_type *type) {
                                                 ^
/Users/atman/Dropbox/Projects/code/opp/cixl/src/cixl/cx.c:135:5: error: implicit declaration of function 'set' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    set(id_tok->as_ptr, NULL);
    ^
/Users/atman/Dropbox/Projects/code/opp/cixl/src/cixl/cx.c:142:42: error: function definition is not allowed here
    bool push_type(struct cx_type *type) {
                                         ^
/Users/atman/Dropbox/Projects/code/opp/cixl/src/cixl/cx.c:160:44: error: implicit declaration of function 'push_type' is invalid in
      C99 [-Werror,-Wimplicit-function-declaration]
      } else if (t->type == CX_TTYPE() && !push_type(t->as_ptr)) {
                                           ^
4 errors generated.
make[2]: *** [CMakeFiles/cixl.dir/src/cixl/cx.c.o] Error 1
make[1]: *** [CMakeFiles/cixl.dir/all] Error 2
make: *** [all] Error 2
```

Leading me to think that `open_memstream` has some functions which the BSD memstream does not....

**Comment by mnemnion** [comment]
Opened up a [PR])(https://github.com/basic-gongfu/cixl/pull/3) with the memstream code incorporated per @basic-gongfu 's suggestions

It doesn't work, mind you

**Comment by ephetic** [comment]
@basic-gongfu  What OS are you building on?  I might set up a docker container to still be able to play with cixl.

**Comment by ephetic** [comment]
Progress:
- added memstream source and include as in above commented.  Fixed open_memstream issue, but yielded new error about nested functions -- clang doesn't support them, so:
- `CC=gcc-7 CXX=g++-7 cmake ..` gets past nested function error but yields 
```
src/cixl/parse.c:437:14: error: implicit declaration of function 'fmemopen'; did you mean 'freopen'? [-Werror=implicit-function-declaration]
   FILE *is = fmemopen ((void *)in, strlen(in), "r");
              ^~~~~~~~
              freopen
```

This appears to be another GNU library that doesn't exist on Darwin.  Have found ports, but haven't made them work yet.

**Comment by basic-gongfu** [comment]
Nice work so far. I fixed the missing include and the format specifier.
I'm on Kubuntu, but I suspect most Linuxes/BSDs would work out of the box.

**Comment by isaachier** [comment]
This is still an issue because clang doesn't support inner functions. Been trying to fix locally and will submit PR if I get around to it soon.
